// John Walter and Evan Schulte
// ECE 3220 - Final Project

#ifndef MAINWINDOW_H
#define MAINWINDOW_H
#include <string>
#include <QMainWindow>
#include <iostream>
using namespace std;
namespace Ui {
class MainWindow;
}

// MainWindow class
class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    // strings below are used when displaying patient and owner names
    string patient_in;
    string owner_in;
    string device_in;
    void updateDisplay(); // updates the MainWindow display
    explicit MainWindow(QWidget *parent = 0); // constructor
    ~MainWindow(); // destructor

private slots: // generated by Qt
    void on_pushButton_clicked();       // method for the New Patient button
    void on_update_clicked();           // method for the update button
    void on_edit_patient_clicked();     // method for the edit patient button
    void on_delete_patient_clicked();   // method or the delete button

private:
    Ui::MainWindow *ui; // used by Qt for the user interface
};

// We plan to change the classes below to be more efficient

// Dog class
class Dogs : MainWindow {
    private:
    public:
        // stores patient information
        string patient;
        string owner = " ";
        string medication = " ";
        string treatment = " ";
        string food = " ";
        string food_amount = " ";
        string device = " ";
        bool own_food = false;
        bool leash = false;
        bool toys = false;
        bool bed_blanket = false;
        bool carrier = false;
        

        Dogs(){} // constructor does nothing but needed to create object
        //~Dogs(){} // more efficient to let Qt handle the destruction of objects because they are a subclass of a Qt class

};

// Cat Class
class Cats : MainWindow{
    private:
    public:
        // stores patient information
        string patient;
        string owner;
        string medication;
        string treatment;
        string food;
        string food_amount;
        string device;
        bool leash;
        bool own_food;
        bool carrier;
        bool toys;
        bool bed_blanket;
        void push();

        // constructor does nothing but needed to create object
        //~Cats(){} // more efficient to let Qt handle the destruction of objects because they are a subclass of a Qt class

};

#endif // MAINWINDOW_H
