// John Walter and Evan Schulte
// ECE 3220 - Final Project

#ifndef MAINWINDOW_H
#define MAINWINDOW_H
#include <string>
#include <QMainWindow>
#include <iostream>
using namespace std;
namespace Ui {
class MainWindow;
}

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    string patient_in;
    string owner_in;
    string device_in;
    void updateDisplay();
    explicit MainWindow(QWidget *parent = 0);
    ~MainWindow();

private slots: // generated by Qt
    void on_pushButton_clicked();

    void on_update_clicked();

    void on_edit_patient_clicked();

private:
    Ui::MainWindow *ui;
};

// We plan to change the classes below to be more efficient

// Dog class
class Dogs : MainWindow {
    private:
    public:
        string patient;
        string owner = " ";
        string medication = " ";
        string treatment = " ";
        string food = " ";
        string food_amount = " ";
        string device = " ";
        bool own_food = false;
        bool leash = false;
        bool toys = false;
        bool bed_blanket = false;
        bool carrier = false;
        void push();
        Dogs(){}
        void printPatient(){cout << patient << endl;}
};

// Cat Class
class Cats : MainWindow{
    private:
    public:
        string patient;
        string owner;
        string medication;
        string treatment;
        string food;
        string food_amount;
        string device;
        bool leash;
        bool own_food;
        bool carrier;
        bool toys;
        bool bed_blanket;
        void push();
        Cats(){}
        void printPatient(){cout << patient << endl;}
};

#endif // MAINWINDOW_H
