// John Walter and Evan Schulte
// ECE 3220 - Final Project

#ifndef NEWPATIENTWINDOW_H
#define NEWPATIENTWINDOW_H

#include <QWidget>
#include <string>
#include <vector>

using namespace std;

namespace Ui {
class NewPatientWindow;
}

class NewPatientWindow : public QWidget
{
    Q_OBJECT

public:
    explicit NewPatientWindow(QWidget *parent = 0); // constructor for a new patient
    explicit NewPatientWindow(QWidget *parent, QString device); // constructor for a current patient to be edited
    int pushInfo(string);
    ~NewPatientWindow();

private slots: // generated by Qt
    void on_push_clicked();

private:
    Ui::NewPatientWindow *ui;
};

#endif // NEWPATIENTWINDOW_H
